@csharp_rest_api_HostAddress = http://127.0.0.1:5001

GET {{csharp_rest_api_HostAddress}}/healthz
Accept: application/json

###

GET {{csharp_rest_api_HostAddress}}/api/todos
Accept: application/json

###

POST {{csharp_rest_api_HostAddress}}/api/todos
Content-Type: application/json

{
  "title": "Prepare startup demo",
  "isDone": false
}

###
